spring:
  application:
    name: analytics-service
  config:
    # Esta línea es crucial: le dice al servicio que busque el resto de su configuración en el Config Server
    import: "optional:configserver:http://config-server:8888"
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/