server:
  port: 8085

spring:
  cloud:
    function:
      definition: consumirNotificacion
    stream:
      bindings:
        consumirNotificacion-in-0:
          destination: pagos-topic # Escucha el mismo tópico donde Pagos publica el resultado
          group: notificaciones-group # Un grupo distinto para que Kafka le entregue una copia también a este servicio
      kafka:
        binder:
          brokers: kafka:9092