server:
  port: 8080

spring:
  application:
    name: ordenes-service
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: consumirRespuestaPago
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        ordenes-topic-out-0:
          destination: ordenes-topic
        consumirRespuestaPago-in-0:
          destination: pagos-topic
          group: ordenes-group

resilience4j:
  circuitbreaker:
    instances:
      pagosCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
          # Hace que el Circuit Breaker aparezca con lujo de detalles en /actuator/health
        registerHealthIndicator: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# --- NUEVA SECCIÓN: MONITOREO CON ACTUATOR Y PROMETHEUS ---
# Aquí habilitamos los endpoints necesarios para que Grafana pueda leer el estado del sistema
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics # Exponemos Prometheus al exterior
  endpoint:
    health:
      show-details: always # Permite ver el estado detallado de los componentes
  metrics:
    export:
      prometheus:
        enabled: true # Activa específicamente el formato de datos para Prometheus
  health:
    circuitbreakers:
      enabled: true # Fundamental: permite ver si el CB está OPEN o CLOSED vía HTTP