server:
  port: 8080

spring:
  application:
    name: ordenes-service
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: consumirRespuestaPago
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        ordenes-topic-out-0:
          destination: ordenes-topic
        consumirRespuestaPago-in-0:
          destination: pagos-topic
          group: ordenes-group

resilience4j:
  circuitbreaker:
    instances:
      pagosCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
