server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # --- CONFIGURACIÓN DE KAFKA ---
  cloud:
    stream:
      kafka:
        binder:
          # Usamos "kafka" porque ese es el nombre del servicio en tu docker-compose
          brokers: kafka:9092
      bindings:
        # Este nombre debe coincidir con el primer parámetro de streamBridge.send("ordenes-topic", ...)
        ordenes-topic:
          destination: ordenes-topic
          content-type: application/json