server:
  port: 8080

spring:
  application:
    name: ordenes-service
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      # Definimos el nombre del Bean que procesa la respuesta del pago
      definition: consumirRespuestaPago
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        # Salida: Envía la orden creada
        ordenes-topic-out-0:
          destination: ordenes-topic
        # ENTRADA: Recibe la confirmación del pago (ESTO ES LO QUE FALTABA)
        consumirRespuestaPago-in-0:
          destination: pagos-topic
          group: ordenes-group

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}