server:
  port: 8004

spring:
  cloud:
    function:
      definition: consumirOrden # Nombre exacto del @Bean en PagoConsumerConfig
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        consumirOrden-in-0:    # Formato: nombreBean-in-index
          destination: ordenes-topic
          group: pagos-group
        pagos-topic-out-0:      # Para que streamBridge sepa a dónde enviar la confirmación
          destination: pagos-topic

  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true