server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
          physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl