server:
  port: 8005
spring:
  application:
    name: notificaciones-service
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: notificaciones-group
      auto-offset-reset: earliest
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        ordenes-in-0:
          destination: ordenes-topic
          group: notificaciones-group
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/