server:
  port: 8002
spring:
  application:
    name: productos-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: productos_db
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health