server:
  port: 8006
spring:
  application:
    name: analytics-service
  redis:
    host: redis
    port: 6379
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: analytics-group
      auto-offset-reset: earliest
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/